apiVersion: fn.kpt.dev/v1alpha1
kind: ApplyReplacements
metadata:
  name: propagate-name
  annotations:
    config.kubernetes.io/local-config: "true"
replacements:
- source:
    kind: ConfigMap
    name: kptfile.kpt.dev
    fieldPath: data.name
  targets:
  - select:
      kind: NFDeployment
    fieldPaths:
    - metadata.name
  - select:
      kind: Interface
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/owner]
  - select:
      kind: Dependency
    fieldPaths:
    - metadata.annotations.[specializer.nephio.org/owner]
      