apiVersion: req.nephio.org/v1alpha1
kind: Dependency
metadata:
  name: amf
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.cucp-0-ffffff
    specializer.nephio.org/namespace: example
spec:
  packageName: oai-amf
  injectors:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFDeployment