apiVersion: req.nephio.org/v1alpha1
kind: DataNetwork
metadata:
  name: internet
  annotations:
    config.kubernetes.io/local-config: "true"
    specializer.nephio.org/owner: workload.nephio.org/v1alpha1.NFDeployment.amf-example
    specializer.nephio.org/namespace: example
spec: